//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAmerica.ErpHook.ConsoleProgram.ErpService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.marketamerica.com/", ConfigurationName="ErpService.ErpHook")]
    public interface ErpHook {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse setErpData(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse> setErpDataAsync(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData request);
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse test(MarketAmerica.ErpHook.ConsoleProgram.ErpService.test request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse> testAsync(MarketAmerica.ErpHook.ConsoleProgram.ErpService.test request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setErpData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setErpData", Namespace="http://api.marketamerica.com/", Order=0)]
        public MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataBody Body;
        
        public setErpData() {
        }
        
        public setErpData(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setErpDataBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public setErpDataBody() {
        }
        
        public setErpDataBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setErpDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setErpDataResponse", Namespace="http://api.marketamerica.com/", Order=0)]
        public MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponseBody Body;
        
        public setErpDataResponse() {
        }
        
        public setErpDataResponse(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setErpDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public setErpDataResponseBody() {
        }
        
        public setErpDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class test {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="test", Namespace="http://api.marketamerica.com/", Order=0)]
        public MarketAmerica.ErpHook.ConsoleProgram.ErpService.testBody Body;
        
        public test() {
        }
        
        public test(MarketAmerica.ErpHook.ConsoleProgram.ErpService.testBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class testBody {
        
        public testBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testResponse", Namespace="http://api.marketamerica.com/", Order=0)]
        public MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponseBody Body;
        
        public testResponse() {
        }
        
        public testResponse(MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class testResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public testResponseBody() {
        }
        
        public testResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ErpHookChannel : MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErpHookClient : System.ServiceModel.ClientBase<MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook>, MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook {
        
        public ErpHookClient() {
        }
        
        public ErpHookClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErpHookClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErpHookClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErpHookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook.setErpData(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData request) {
            return base.Channel.setErpData(request);
        }
        
        public string setErpData(string arg0) {
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData inValue = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData();
            inValue.Body = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataBody();
            inValue.Body.arg0 = arg0;
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse retVal = ((MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook)(this)).setErpData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse> MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook.setErpDataAsync(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData request) {
            return base.Channel.setErpDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse> setErpDataAsync(string arg0) {
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData inValue = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData();
            inValue.Body = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataBody();
            inValue.Body.arg0 = arg0;
            return ((MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook)(this)).setErpDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook.test(MarketAmerica.ErpHook.ConsoleProgram.ErpService.test request) {
            return base.Channel.test(request);
        }
        
        public string test() {
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.test inValue = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.test();
            inValue.Body = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.testBody();
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse retVal = ((MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook)(this)).test(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse> MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook.testAsync(MarketAmerica.ErpHook.ConsoleProgram.ErpService.test request) {
            return base.Channel.testAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse> testAsync() {
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.test inValue = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.test();
            inValue.Body = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.testBody();
            return ((MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook)(this)).testAsync(inValue);
        }
    }
}
