//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAmerica.ErpHook.ConsoleProgram.ErpService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.marketamerica.com/", ConfigurationName="ErpService.ErpHook")]
    public interface ErpHook {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse setErpData(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse> setErpDataAsync(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceResponse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse test(MarketAmerica.ErpHook.ConsoleProgram.ErpService.test request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse> testAsync(MarketAmerica.ErpHook.ConsoleProgram.ErpService.test request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.marketamerica.com/")]
    public partial class erpHookResponse : serviceResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(erpHookResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.marketamerica.com/")]
    public abstract partial class serviceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseError[] errorsField;
        
        private universeResponse legacyResponseField;
        
        private statusType statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public responseError[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public universeResponse legacyResponse {
            get {
                return this.legacyResponseField;
            }
            set {
                this.legacyResponseField = value;
                this.RaisePropertyChanged("legacyResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public statusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.marketamerica.com/")]
    public partial class responseError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private severityType severityField;
        
        private bool severityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public severityType severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool severitySpecified {
            get {
                return this.severityFieldSpecified;
            }
            set {
                this.severityFieldSpecified = value;
                this.RaisePropertyChanged("severitySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.marketamerica.com/")]
    public enum severityType {
        
        /// <remarks/>
        CRITICAL,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        VALIDATION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.marketamerica.com/")]
    public partial class universeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverControlCodeField;
        
        private string serverControlNameField;
        
        private System.DateTime serverLastDateField;
        
        private bool serverLastDateFieldSpecified;
        
        private System.DateTime serverLastTimeField;
        
        private bool serverLastTimeFieldSpecified;
        
        private string serverMessageField;
        
        private int serverStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serverControlCode {
            get {
                return this.serverControlCodeField;
            }
            set {
                this.serverControlCodeField = value;
                this.RaisePropertyChanged("serverControlCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serverControlName {
            get {
                return this.serverControlNameField;
            }
            set {
                this.serverControlNameField = value;
                this.RaisePropertyChanged("serverControlName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime serverLastDate {
            get {
                return this.serverLastDateField;
            }
            set {
                this.serverLastDateField = value;
                this.RaisePropertyChanged("serverLastDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serverLastDateSpecified {
            get {
                return this.serverLastDateFieldSpecified;
            }
            set {
                this.serverLastDateFieldSpecified = value;
                this.RaisePropertyChanged("serverLastDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime serverLastTime {
            get {
                return this.serverLastTimeField;
            }
            set {
                this.serverLastTimeField = value;
                this.RaisePropertyChanged("serverLastTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serverLastTimeSpecified {
            get {
                return this.serverLastTimeFieldSpecified;
            }
            set {
                this.serverLastTimeFieldSpecified = value;
                this.RaisePropertyChanged("serverLastTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string serverMessage {
            get {
                return this.serverMessageField;
            }
            set {
                this.serverMessageField = value;
                this.RaisePropertyChanged("serverMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int serverStatus {
            get {
                return this.serverStatusField;
            }
            set {
                this.serverStatusField = value;
                this.RaisePropertyChanged("serverStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.marketamerica.com/")]
    public enum statusType {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        TIMEOUT,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setErpData", WrapperNamespace="http://api.marketamerica.com/", IsWrapped=true)]
    public partial class setErpData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.marketamerica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public setErpData() {
        }
        
        public setErpData(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setErpDataResponse", WrapperNamespace="http://api.marketamerica.com/", IsWrapped=true)]
    public partial class setErpDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.marketamerica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MarketAmerica.ErpHook.ConsoleProgram.ErpService.erpHookResponse @return;
        
        public setErpDataResponse() {
        }
        
        public setErpDataResponse(MarketAmerica.ErpHook.ConsoleProgram.ErpService.erpHookResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="test", WrapperNamespace="http://api.marketamerica.com/", IsWrapped=true)]
    public partial class test {
        
        public test() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testResponse", WrapperNamespace="http://api.marketamerica.com/", IsWrapped=true)]
    public partial class testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.marketamerica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public testResponse() {
        }
        
        public testResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ErpHookChannel : MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErpHookClient : System.ServiceModel.ClientBase<MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook>, MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook {
        
        public ErpHookClient() {
        }
        
        public ErpHookClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErpHookClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErpHookClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErpHookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook.setErpData(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData request) {
            return base.Channel.setErpData(request);
        }
        
        public MarketAmerica.ErpHook.ConsoleProgram.ErpService.erpHookResponse setErpData(string arg0) {
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData inValue = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData();
            inValue.arg0 = arg0;
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse retVal = ((MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook)(this)).setErpData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse> MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook.setErpDataAsync(MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData request) {
            return base.Channel.setErpDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpDataResponse> setErpDataAsync(string arg0) {
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData inValue = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.setErpData();
            inValue.arg0 = arg0;
            return ((MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook)(this)).setErpDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook.test(MarketAmerica.ErpHook.ConsoleProgram.ErpService.test request) {
            return base.Channel.test(request);
        }
        
        public string test() {
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.test inValue = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.test();
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse retVal = ((MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook)(this)).test(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse> MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook.testAsync(MarketAmerica.ErpHook.ConsoleProgram.ErpService.test request) {
            return base.Channel.testAsync(request);
        }
        
        public System.Threading.Tasks.Task<MarketAmerica.ErpHook.ConsoleProgram.ErpService.testResponse> testAsync() {
            MarketAmerica.ErpHook.ConsoleProgram.ErpService.test inValue = new MarketAmerica.ErpHook.ConsoleProgram.ErpService.test();
            return ((MarketAmerica.ErpHook.ConsoleProgram.ErpService.ErpHook)(this)).testAsync(inValue);
        }
    }
}
